### ISSUE TITLE
Nice tools！ how to support domain access; rand content why always zero?

### ISSUE THREAD

**Issue by rikewang** [igneous-systems/s3bench#7]
I want to test ceph rgw(S3), my domain like s3test.ceph.com, I use the blow command
./s3bench -accessKey=8P3Z50DD281CO79xxxx -accessSecret=yNZJmJ9j8uPkqch1BjkCwpdCATDxxxxxxxx  -bucket=test -endpoint=http://s3test.ceph.com:80    -numClients=256 -numSamples=4096  -objectNamePrefix=loadgen -objectSize=10485760 

but errors appear like
Write operation completed in 0.08s (1/8) - 0.00MB/s, error: NoSuchBucket: 
	status code: 404, request id: tx000000000000000000f2a-0059a1700a-138fb-default, host id: 

BTW: the content why always zero, it affect test result?, but i see code rand.Read?
I think IOPS is neccessary~
THX~

**Comment by jeffdh** [comment]
Thanks for pointing out the non-random content bug!  I've addressed that in the latest commit.  Happy to accept a patch for bucket domains.
